services:
  - type: web
    name: gameboxservice
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    domains:
      - gameboxservice.onrender.com
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
